[project]
authors = ["Carlotta Sartore <carlotta.sartore@iit.it>"]
channels = ["conda-forge"]
description = "Suite of parametrized controller with simulation environments for co-design of Humanoid Robots"
name = "comodo"
platforms = ["linux-64"]
version = "0.0.0"
repository = "https://github.com/ami-iit/comodo"
readme = "README.md"
license-file = "LICENSE"

[activation]
# To avoid issue with git-lfs, see https://github.com/prefix-dev/pixi/issues/2000
env = { GIT_LFS_SKIP_SMUDGE = "1" }

[dependencies]
# bipedal-locomotion-framework and manifpy have pinned build dependencies
# due to https://github.com/ami-iit/bipedal-locomotion-framework/issues/885
bipedal-locomotion-framework = { version = "==0.18.0", build = "ha770c72_15" }
manifpy = { version = "==0.0.5", build = "py310hf5d888b_0" }
idyntree = "*"
adam-robotics = "*"
mujoco = "*"
mujoco-python-viewer = "*"
matplotlib = ">=3.9.2,<4"
urllib3 = "*"
urchin = "*"
resolve-robotics-uri-py = "*"
notebook = "*"
rod = "*"
ipykernel = "*"
mesalib = "*"
optuna = ">=4.0.0,<5"
cmaes = ">=0.11.1,<0.12"
plotly = ">=5.24.1,<6"
casadi = "<=3.6.6"
nbformat = ">=5.10.4,<6"
python-kaleido = ">=0.2.1,<0.3"
scikit-learn = ">=1.5.2,<2"
wandb = ">=0.17.3,<0.18"
# jaxsim = ">=0.4.2"

[pypi-dependencies]
# jaxsim = { git = "https://github.com/ami-iit/jaxsim.git", rev="visco_elastic_contacts", extras = ["all"]}
jaxsim = { path = "../jaxsim", extras = ["all"], editable = true }
urdfmodifiers = { git = "https://github.com/CarlottaSartore/urdf-modifiers.git", rev = "scalar_modification" }
comodo = { path = "./", editable = true }
optuna-integration = { version = ">=4.0.0, <5", extras = ["wandb"] }
